packagegroup-venus-base: remove ffmpeg
nobody uses it, and it doesn't build because of a license error. Removing
is less effort than fixing.

ERROR: Nothing PROVIDES 'ffmpeg' (but /media/venusbuilds/wipbbbjethro/sources/meta-victronenergy/meta-venus/recipes-packagegroups/packagegroup-venus-base.bb DEPENDS on or otherwise requires it)
ERROR: libav PROVIDES ffmpeg but was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
NOTE: Runtime target 'packagegroup-venus-base' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-venus-base', 'ffmpeg']
ERROR: Required build target 'venus-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['venus-image', 'packagegroup-venus-base', 'ffmpeg']