fix warning about deamontools-run selection
commit a840fe17da5 "fix note about deamontools-run selection"
Introduces warnings like these on newer OE versions:

WARNING: Variable key RDEPENDS_${PN} (  python-dbus 	python-lxml ) replaces original key RDEPENDS_localsettings ( daemontools-run).
WARNING: Variable key RDEPENDS_${PN} (  python-dbus 	python-lxml ) replaces original key RDEPENDS_localsettings ( daemontools-run).

Prevent such warnings.

Rename the venus daemontools-run to make it venus specific to prevent this error:

ERROR: Multiple .bb files are due to be built which each provide daemontools-run
 This usually means one provides something the other doesn't and should.